---
version: 0.0.{build}-beta
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off

before_build:
- dotnet restore --no-cache

build:
  publish_nuget: true

artifacts:
- path: '**\*.nupkg'

nuget:
  disable_publish_on_pr: true

deploy:
- provider: NuGet
  api_key:
    secure: fWZBstsWHg5AQokmAwTxmT7Q4Zn14KjJQL00CuVMXMlaFDLMtxzpgeiF1ojqPKcd
  skip_symbols: true
  artifact: /.*\.nupkg/