name: .NET CI
on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/kerberos-lib.yml'
env:
  DOTNET_CORE_VERSION: '8.0.x'
  MAJOR_VERSION: '8'
  MINOR_VERSION: '0'
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'

jobs:
  build_test_pack_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Set version
      id: set_version
      run: |
        if [ ${{ github.ref }} = 'refs/heads/master' ]; then
          
          echo "VERSION=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }}-dev" >> $GITHUB_OUTPUT
        fi        

    - name: Create Git tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a v${{ steps.set_version.outputs.VERSION }} -m "Version ${{ steps.set_version.outputs.VERSION }}"
        git push origin v${{ steps.set_version.outputs.VERSION }}
    
    - name: Build
      run: |        
        dotnet build -c Release --nologo        

    
    - name: Pack NuGet package
      run: |        
        dotnet pack -c Release -o out /p:Version=${{ steps.set_version.outputs.VERSION }}
    
    - name: Push NuGet package
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SOURCE }} --skip-duplicate